nucleotide = ['A', 'T', 'C', 'G']
DNA_reverse_Complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}

# complement function
def complement(sequence):
    complement_seq = ''
    for nuc in sequence:
        complement_seq += DNA_reverse_Complement[nuc]
    
    return complement_seq

# reverse complement function
def reverse_complement(sequence):
    reverse_seq = sequence[::-1]
    reverse_seq = complement(reverse_seq)

    return reverse_seq


sequence = "TGTATGCAACCCATTGAGTACACAGATCACCAAGTTCCACTTAGTGAAAAAACCCAAAGCGTACCAGCAACCAAAGGGGCAGAGGGCTCATGGACTCAGAGGGCCCGACCTCGGTTGTGAAACGGGCCTAGATGCAGAAACACGCAATAGCAAACCCTCAGCGTAAACGTTTGCGATTCATCAGCTCTTCGCTTTGAAAGCGGTGGCGATGGCTGGCTCACCCTATAAGCCGCCAACCTCGAGTTGGGTTTTCCGGTCTGGTCCGGCGTAGCGCGTAGTGAAGTAAATGTGTTGCCTACTCCAAGTGTCCCTTCACCTTGGGCACAGCGAACCCCGCAACGATGTGCTGCAGAAAGCGCGATAACCATACTAAATTTGCACCTCAGACAACAACCGATAGGTGGCTACCTCCACAGTGTTGGAAAAGCTAGAAAATCGTACATTCATCGATATCATACGGTTTAATAGACGGGACGGCCCGCGATCGCTCTGGAGTAGCATGCCTTGCCACTCAGGTCTAAGCGTGAAACGCCTCACGGTAAATACGTTTGAGACTGTCGTAATTATGACCTCAGCTGAATGCTAAGTGAGGAATCCGCGTCCAAGTCGAGAATTGACAGGCATGCGGGGCCTCGTCAATGTACGGCCCCGATACGCTCACACTGCTCCGCAGTTTGGCCTTGGACCAAAAAATGTTTGCTAGTGGACATAATGAGGAATTGCCGATGTTTTAATTATCAACCCGCCACAAATTTGTACAAACTGGCCGCCCAATGGTCGATTATGTCCAGATTACCTTATGAGGGTCTCACTCTGGGCT"

print(reverse_complement(sequence))